# Generated by Django 4.2.1 on 2023-05-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_marks_student_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='studentapp.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
